[package]
name = "subnet-wcp-chain"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
alloy = { version = "1.0", features = ["full"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }


