[package]
name = "subnet-wcp-event"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
alloy = { version = "1.0", features = ["full"] }
tokio = { version = "1", features = ["rt-multi-thread", "macros", "time"] }
tracing = "0.1.41"

