[package]
name = "subnet-wcp-storage"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
tonic = { version = "0.11", features = ["tls"] }
prost = "0.12"
prost-types = "0.12"
tracing = "0.1.41"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

