[package]
name = "subnet-wcp-persistence"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rocksdb = { version = "0.22", default-features = false, features = ["zstd", "lz4"] }
thiserror = "1.0"

